try:
    d = 2 + "hola"
except Exception as ex:
    print("Ha habido una exception:", type(ex))
    